### ISSUE TITLE
Use of uninitialized value - Mac OSX perl5.16

### ISSUE THREAD

**Issue by kurthindenburg** [kazeburo/POSIX-strftime-Compiler#3]
Trying to run the example code on the website on Mac OSX perl 5.16 (is there a typo in the example code?  should be ; end of line 3)

Use of uninitialized value $fmt in substitution (s///) at /opt/local/lib/perl5/vendor_perl/5.16.3/POSIX/strftime/Compiler.pm line 303.
Use of uninitialized value $fmt in substitution (s///) at /opt/local/lib/perl5/vendor_perl/5.16.3/POSIX/strftime/Compiler.pm line 304.
Use of uninitialized value $fmt in substitution (s///) at /opt/local/lib/perl5/vendor_perl/5.16.3/POSIX/strftime/Compiler.pm line 305.
Use of uninitialized value $sprintf_fmt in pattern match (m//) at /opt/local/lib/perl5/vendor_perl/5.16.3/POSIX/strftime/Compiler.pm line 310.
Use of uninitialized value $sprintf_fmt in substitution (s///) at /opt/local/lib/perl5/vendor_perl/5.16.3/POSIX/strftime/Compiler.pm line 317.
Use of uninitialized value $sprintf_fmt in concatenation (.) or string at /opt/local/lib/perl5/vendor_perl/5.16.3/POSIX/strftime/Compiler.pm line 322.
Use of uninitialized value $posix_fmt in substitution (s///) at /opt/local/lib/perl5/vendor_perl/5.16.3/POSIX/strftime/Compiler.pm line 329.
Use of uninitialized value $posix_fmt in concatenation (.) or string at /opt/local/lib/perl5/vendor_perl/5.16.3/POSIX/strftime/Compiler.pm line 343.
Sun, 30 Nov 2014 13:04:13 -0500%

**Comment by kazeburo** [comment]
released 0.41.
